# Matrix multiplication

In [1]:
import numpy as np

In [28]:
np.random.seed(12)
A = np.random.randint(low=1, high=10, size=[2,2])

In [29]:
print('\nOriginal matrix value')
display(A)

print('\nDot product')
display(A @ A)

print('\nDot product with their own transpose')
display(A @ A.T)


Original matrix value


array([[7, 2],
       [3, 4]])


Dot product


array([[55, 22],
       [33, 22]])


Dot product with their own transpose


array([[53, 29],
       [29, 25]])

## Scalars, Vectors, Matrices, and Tensors

In [86]:
np.random.seed(12)

# A scalar
s1 = np.random.randint(1,10,1)
s2 = np.random.randint(1,10,1)

# A vector
v = np.random.randint(1,10,[5,1])

# A transposed vector
v_T = v.T

# A set of S, an index of excluded items in v
S = np.random.choice(np.arange(v.size), 3)

# Exclude S from v
v_wo_S = np.expand_dims(np.delete(np.squeeze(v.T), S),0).T

# A matrix
M = np.random.randint(1,10,[2,2])

# A tensor (matrix with more than 2D)
T3 = np.random.randint(1,10,[2,2,2])
T4 = np.random.randint(1,10,[2,2,2,2])

# A matrix's transpose, mirror across a diagonal line
M_T = M.T

# A vector notation in inline text
v_i = v_T.T
assert (v_i.shape == v.shape) and (v_i.all() == v.all())

# Matrix addition
M2 = np.random.randint(1,10,[2,2])
Madd = M + M2

# Matrix multiplication with scalar
Ms = s1 * M + s2



In [92]:
np.expand_dims(np.delete(np.squeeze(v.T), S),0).T

array([[3],
       [4],
       [1]])

In [90]:
np.delete(np.squeeze(v.T), S)

array([3, 4, 1])

In [51]:
v.T.shape

(5,)

In [84]:
v.size

np.random.choice(np.arange(v.size), 3)

array([3, 4, 0])

In [82]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interva